import test from 'node:test';
import assert from 'node:assert/strict';
import { DatabaseSync } from 'node:sqlite';
import { readFileSync } from 'node:fs';
import { randomUUID } from 'node:crypto';
import {canReview,validateDecision,saveDecision,requireSameOrigin,readBoundedJson} from '../lib/review-core.mjs';
const item={id:'website:00000000-0000-4000-8000-000000000001',fingerprint:'a'.repeat(64),group:'held',issues:[],website:null,source:null};
const user={userId:'owner-test',email:'owner@example.invalid'};
const input=(extra={})=>({id:item.id,fingerprint:item.fingerprint,revision:0,requestId:randomUUID(),decision:'ok',fields:{sku:'TEST-01',name:'Test part',brand:'Example'},note:'',...extra});
function database(){const sql=new DatabaseSync(':memory:');sql.exec(readFileSync(new URL('../drizzle/0000_robust_junta.sql',import.meta.url),'utf8'));sql.prepare("INSERT INTO review_state(id,revision,ready,metadata) VALUES(1,0,1,'{}')").run();return {sql,prepare(query){return {bind(...args){const run=()=>sql.prepare(query).run(...args);return {run:async()=>run(),first:async()=>sql.prepare(query).get(...args)||null,all:async()=>({results:sql.prepare(query).all(...args)}),_run:run};}};},async batch(statements){sql.exec('BEGIN');try{const result=statements.map(s=>s._run());sql.exec('COMMIT');return result;}catch(e){sql.exec('ROLLBACK');throw e;}}};}
test('only the configured owner can access; an enrolled ID must also match',()=>{assert.equal(canReview(user,user.email,null),true);assert.equal(canReview(null,user.email,null),false);assert.equal(canReview(user,'',null),false);assert.equal(canReview({...user,email:'stranger@example.invalid'},user.email,null),false);assert.equal(canReview({...user,userId:'stranger'},user.email,{owner_id:user.userId}),false);});
test('identity and fingerprint validation fail closed',()=>{assert.throws(()=>validateDecision(input({fingerprint:'stale'}),item,user.userId));for(const fields of [{sku:'',name:'Part',brand:'Example'},{sku:'a',name:'Part',brand:'Unknown'},{sku:'a',name:'Our cost $12',brand:'Example'},{sku:'a/../b',name:'Part',brand:'Example'}])assert.throws(()=>validateDecision(input({fields}),item,user.userId));assert.throws(()=>validateDecision(input({decision:'fix'}),item,user.userId));assert.throws(()=>validateDecision(input({revision:-1}),item,user.userId));assert.throws(()=>validateDecision(input(),{...item,group:'completed'},user.userId));});
test('durable save, idempotent retry, conflict safety, and audit history',async()=>{const db=database(),first=input();const saved=await saveDecision(db,first,item,user);assert.equal(saved.revision,1);assert.equal(db.sql.prepare('SELECT COUNT(*) n FROM review_history').get().n,1);assert.equal((await saveDecision(db,first,item,user)).revision,1);await assert.rejects(saveDecision(db,input({note:'stale tab'}),item,user),/Another tab/);assert.equal(db.sql.prepare('SELECT revision FROM review_state').get().revision,1);await assert.rejects(saveDecision(db,input({revision:10}),item,user),/Another tab/);await assert.rejects(saveDecision(db,input({revision:1}),item,{...user,userId:'stranger'}),/Another tab/);const second=await saveDecision(db,input({revision:1,decision:'no',note:'Leave off'}),item,user);assert.equal(second.revision,2);const h=JSON.parse(db.sql.prepare('SELECT payload FROM review_history WHERE revision=2').get().payload);assert.equal(h.before.decision,'ok');assert.equal(h.after.decision,'no');assert.equal(db.sql.prepare('SELECT owner_id FROM review_state').get().owner_id,user.userId);db.sql.close();});
test('sealed readiness is required to save',async()=>{const db=database();db.sql.exec('UPDATE review_state SET ready=0');await assert.rejects(saveDecision(db,input(),item,user),/Another tab/);assert.equal(db.sql.prepare('SELECT COUNT(*) n FROM review_decisions').get().n,0);db.sql.close();});
test('same-origin POST and body limit are required',async()=>{const req=(origin,body='{}')=>new Request('https://review.example/api/decision',{method:'POST',headers:{origin,'content-type':'application/json'},body});assert.doesNotThrow(()=>requireSameOrigin(req('https://review.example')));assert.throws(()=>requireSameOrigin(req('https://attacker.example')));assert.deepEqual(await readBoundedJson(req('https://review.example'),20),{});await assert.rejects(readBoundedJson(req('https://review.example','x'.repeat(30)),20));});
