export const salesHtml = `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>DTBP · Slow-selling items</title>
<style>
:root{font:16px/1.5 system-ui,-apple-system,Segoe UI,sans-serif;color:#172a3b;background:#f4f6f8}*{box-sizing:border-box}body{margin:0}a{color:#165d93}button,input,select{font:inherit}button,input,select{padding:10px 14px;border:1px solid #bdc9d5;border-radius:7px;background:#fff;color:inherit}button{cursor:pointer;font-weight:600}button:disabled{opacity:.6;cursor:wait}button,a,input,select{outline-offset:3px}header{background:#fff;border-bottom:1px solid #d9e0e7;padding:22px 28px;display:flex;justify-content:space-between;gap:18px;align-items:center}h1{font-size:26px;margin:4px 0}h2{font-size:21px;margin:0}p{margin:6px 0}.muted{color:#566979;font-size:14px}.tools,.filters{display:flex;gap:12px;flex-wrap:wrap;align-items:center}main{padding:24px 28px;max-width:1700px;margin:auto}.folders{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px;margin:18px 0}.folder{text-align:left;padding:17px 20px;border-color:#d9e0e7}.folder strong{display:block;font-size:25px;margin-top:4px}.folder[aria-pressed=true]{background:#12334c;color:#fff;border-color:#12334c}.context{background:#eaf1f7;border:1px solid #ccdae6;border-radius:8px;padding:14px 18px;margin:14px 0;font-size:14px}.filters{margin:18px 0}.filters input{flex:1;min-width:200px}.sheet{background:#fff;border:1px solid #d9e0e7;border-radius:10px;overflow:hidden}.sheet-head{display:flex;justify-content:space-between;gap:14px;align-items:center;padding:18px 20px;border-bottom:1px solid #d9e0e7}.table-scroll{overflow-x:auto}table{border-collapse:collapse;width:100%;text-align:left;font-size:14px}th{background:#f6f8fa;font-weight:600;white-space:nowrap}th,td{padding:14px 18px;border-bottom:1px solid #e4e9ee;vertical-align:top}.part{max-width:620px}.part strong{display:block;margin:4px 0;font-size:16px;overflow-wrap:anywhere}.sku{font-weight:700}.note{display:block;color:#657585;font-size:13px;margin-top:5px;max-width:460px}.stock{display:inline-block;padding:4px 8px;border-radius:5px;background:#eef3f7}.stock.zero,.stock.negative{background:#fff0d9;color:#6d470d}.empty{padding:24px}.pager{display:flex;justify-content:space-between;gap:12px;align-items:center;padding:14px 20px}.notice{margin:12px 0;padding:12px 16px;border:1px solid #d2dbe4;border-radius:7px}.notice:empty{display:none}details{margin-top:22px;font-size:14px}summary{cursor:pointer;font-weight:600}details p{max-width:1000px}.import-row{display:flex;flex-wrap:wrap;gap:12px;margin:14px 0}.footer{font-size:14px;color:#596e7f;margin-top:16px}[hidden]{display:none!important}
@media(max-width:700px){header{padding:16px;display:block}.tools{margin-top:12px}main{padding:12px 16px}.folders{gap:7px}.folder{padding:12px 10px;font-size:14px}.folder strong{font-size:22px}h1{font-size:24px}.sheet-head{align-items:flex-start;flex-direction:column}table,tbody,tr,td{display:block}thead{display:none}tr{padding:14px 16px;border-bottom:1px solid #d9e0e7}td{padding:5px 0;border:0}td[data-label]::before{content:attr(data-label);display:block;font-size:13px;color:#596e7f}.part{max-width:none}.table-scroll{overflow:visible}.pager{padding:12px}input[type=file]{max-width:100%;padding:8px}}
@media print{body{background:white}header .tools,.folders,.filters,.pager,details,#notice,#check-history{display:none!important}header,main{padding:10px}main{max-width:none}.sheet{border:0}table{font-size:11px}th,td{padding:7px}.part strong{font-size:12px}.note,.muted,.footer,.context{font-size:11px}.stock{padding:0;background:none!important}tr{break-inside:avoid}}
</style></head><body>
<header><div><a href="/review">← Catalog review</a><h1>Slow-selling items</h1><p id="as-of" class="muted">Private inFlow sales-history review</p></div><div class="tools"><button id="reload">Reload</button><button id="print" disabled>Print this folder</button><a href="/signout-with-chatgpt?return_to=%2F">Sign out</a></div></header>
<main><div id="notice" class="notice" role="status" aria-live="polite"></div>
<nav class="folders" aria-label="Time since recorded sale"><button class="folder" data-view="6" aria-pressed="true">6–11 months<strong id="count-6">—</strong></button><button class="folder" data-view="12" aria-pressed="false">12–17 months<strong id="count-12">—</strong></button><button class="folder" data-view="18" aria-pressed="false">18+ months<strong id="count-18">—</strong></button></nav>
<p class="context">Use these lists to discuss what to keep selling. Items with no sale found are grouped by their product record’s age and clearly marked. Current recorded stock does not tell us how long an item was out of stock. Nothing here removes an item or changes your saved website decisions.</p>
<div class="filters"><input id="search" type="search" placeholder="Search SKU, title or brand" aria-label="Search slow-selling items"><select id="stock" aria-label="Current recorded stock"><option value="">All stock statuses</option><option value="positive">Stock recorded</option><option value="zero">Zero recorded stock</option><option value="negative">Negative stock — check count</option><option value="unknown">Stock not verified</option></select></div>
<section class="sheet"><div class="sheet-head"><h2 id="folder-title">6–11 months</h2><span id="result-count" class="muted">Loading report…</span></div><div class="table-scroll"><table><thead><tr><th scope="col">Part / recorded brand</th><th scope="col">Last recorded sale</th><th scope="col">Current recorded stock</th></tr></thead><tbody id="rows"></tbody></table></div><p id="empty" class="empty" hidden></p><div class="pager"><button id="prev">Previous</button><span id="page-count" class="muted"></span><button id="next">Next</button></div></section>
<button id="check-history" hidden></button>
<details><summary>How the dates and folders work</summary><p id="coverage"></p><p id="date-basis"></p><p>Each item appears in only one age folder. The cutoffs use calendar months, inclusive of the cutoff day. Items sold within six months, inactive items and services are excluded.</p><p>If no sale is found, the date stays blank and the row says “No recorded sale found.” Its folder uses the age of the inFlow product record, not an invented sale date. Newer records under six months stay out. Missing or future-dated qualifying history is kept in a separate date-check list.</p><p>Stock is a point-in-time inFlow record, not a verified physical count or a promise of availability. No stock quantities or prices appear here.</p></details>
<details><summary>Load an updated private report</summary><p>Choose the prepared DTBP sales-folder JSON file. This updates only this private report. Your catalog choices, notes and saved-for-later items stay untouched.</p><div class="import-row"><input id="report-file" type="file" accept=".json,application/json" aria-label="Prepared private report"><button id="import" disabled>Load report</button></div></details>
<p class="footer">Owner-only report · No automatic deletion, discontinuation or website approval.</p></main><script type="module" src="/sales-app.js?v=20260909"></script></body></html>`;
